name: Main

on: [push, pull_request, workflow_dispatch]

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        shell: bash
        run: |
          set -x
          set -e

          # Build the native binaries
          mkdir -p ./build/native/
          pushd ./build/native/
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=./out/ \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            ../..

          cmake --build . --config Release -j 8
          popd

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Lerna build and test
        shell: bash
        working-directory: ./js2
        run: |
          npm install
          npx lerna bootstrap
          npx lerna run wasm
          npx lerna run build
          npx lerna run test

      - name: Publish
        shell: bash
        working-directory: ./js2
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'develop' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # We only run this step when the build trigger was a push to the develop branch, thus
          # we need to set the fetch-depth to 0 to collect necessary tags so that we can successfully
          # execute this from-git step
          lerna publish from-git --yes --dist-tag next
