name: Main

on: [push, pull_request, workflow_dispatch]

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        shell: bash
        run: |
          set -x
          set -e

          # Build the native binaries
          mkdir -p ./build/native/
          pushd ./build/native/
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=./out/ \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            ../..

          cmake --build . --config Release -j 8
          popd

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Lerna build and test
        shell: bash
        working-directory: ./js2
        run: |
          lerna bootstrap
          lerna run wasm
          lerna run build
          lerna run test

      - name: Publish
        shell: bash
        working-directory: ./js2
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'develop' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # See https://github.com/lerna/lerna/issues/2788 for --no-verify-access reasoning
          #
          # Also, note that Github will not trigger a workflow event for tags in cases where
          # more than three tags are pushed at once:
          # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
          #
          # Therefore we run lerna publish on every build, and set fetch-depth: 0 for the checkout
          # step in this job which will collect all tags. Lerna will then find them and publish if
          # they're there, else skip.
          lerna publish from-git --yes --dist-tag next
